### ISSUE TITLE
Avoid downloading same translation file version

### ISSUE THREAD

**Issue by xipasduarte** [26B/i18n-midoru#22]
When downloading a translations file on any language, if there isn't any change to it, we could end up causing overload on the translation service. To save on this and accelerate the translations step we should add a mechanism to check for changes.

**Detect changes**
This can be different for each service that we support. For now we're only using Localise.biz and they use an HTTP header approach.

**Storing state**
To control this process, we should add a lock file mechanism to our workflow. The lock file will store relevant information regarding the modified dates for each asset, which later are used in the download step. This means that after each download operation we must generate a lock file (for now let's make it a must).

**TODO**
- [x] Add lock file to store information of modified date for each downloaded asset.
- [x] Read from lock file to check if an asset changed before actually downloading.
- [x] Add option to bypass modified validation (globally for now).
- [x] If config for project has changed, then clear lock for that project.
